version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "wandera/jade"
  commit-message:
    prefix: "TRIVIAL: "
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "wandera/jade"
  commit-message:
    prefix: "TRIVIAL: "
