version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unparam
    - unused
    - whitespace
  settings:
    godot:
      exclude:
        - ^ @.*
        - ^ (\d+)(\.|\)).*
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - gosec
        text: G115
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
