name: lint
on:
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: golangci-lint
      uses: wandera/golangci-lint-action@v5
      with:
        version: v1.59.0
        args: --verbose
