name: Test

on:
  pull_request:
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0
    - name: Install Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version-file: go.mod
    - name: Test
      run: make test
